/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "ReservationEmailAPI",
            "endpoint": "https://4gdvu4xlob.execute-api.ap-northeast-1.amazonaws.com/mamascare",
            "region": "ap-northeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://3h3ynlg7ufhkpa6jswlzfiy5lm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yohzlirx2bb6dak7qnfux6qmca",
    "aws_cognito_identity_pool_id": "ap-northeast-1:ff47f56b-9c7b-48c2-910c-aaab825fe615",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_AsxCddHvH",
    "aws_user_pools_web_client_id": "44nbmip5h3nbqn7ltns5mdfok9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "reservationappe8cb5b46a406400688bb1204204b43e69f848-mamascare",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
